### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by aciwarrior** [maK-/scantastic-tool#9]
Reports the following during the start:

Starting masscan 1.0.3 (http://bit.ly/14GZzcT) at 2016-08-10 16:37:11 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 1 hosts [15 ports/host]
xml/scan.xml: No such file or directory
xml/scan.xml: No such file or directory6 remaining, found=0       
Scan completed!
IO Error
Traceback (most recent call last):
  File "/scantastic-tool-master/scantastic.py", line 242, in <module>
    args.port, args.noinsert)
  File "/scantastic-tool-master/scantastic.py", line 133, in scan
    ms.import_es(index, eshost, esport)
  File "/scantastic-tool-master/netscan.py", line 48, in import_es
    port = entry['ports']['port']
TypeError: string indices must be integers, not str

**Comment by abdilahrf** [comment]
same issue haha

**Comment by maK-** [comment]
The problem is that you are running it against one host, which the tool isn't really built for, idea is to scan larger networks/ranges

Only way I can reproduce this :P
